print("Hi")
print("The Updates are causing the machine to boot, slowly")
print("Ubuntu, Fedora, Red Hat or Debian")
print("Ubuntu is my first choice")
print("Fedora is a slick Distro")
print("My Next choice is Red Hat")